import Head from 'next/head'
import { useRouter } from 'next/router';
import DQButton from '../components/DQButton/DQButton'
import { createModal } from '../components/DQModal/DQModal'
import Header from '../components/Header';
import s from './index.module.scss';

export default function Home() {

  const router = useRouter();

  return (
    <>
      <Head>
        <title>DramaQuick</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </Head>

      <Header />

      <main className={s.main}>

        <div className={s.title}>
          <h1>Une nouvelle version de DramaQuiz ⚡</h1>
          <p>DramaQuick est une version de DramaQuiz accélérée ; des questionnaires temoporaires, des sessions de quiz... Tout cela a été créé avec une idée : l'éphémérité !</p>
          <DQButton style='filled' content="Rejoindre une session" onClick={() => createModal({ title: "Modal!", children: (<><h1>Saumon</h1></>) }) && console.log("Clicked")} />
        </div>

        <div className={s.stats}>
          <div className={s.stats_element}>
            <h2>0</h2>
            <span lang="fr">Quiz réalisés</span>
          </div>
          <div className={s.stats_element}>
            <h2>0</h2>
            <span lang="fr">Sessions actives</span>
          </div>
          <div className={s.stats_element}>
            <h2>0</h2>
            <span lang="fr">Participations 💀</span>
          </div>
        </div>

      </main>
    </>
  )
}